export const validationMessage = {
    emptyEmail: 'Please enter your email',
    validEmail: 'Please enter valid email',
    emptyPassword: 'Please enter your password',
    validPassword:
      'Password should be minimum 8 characters contains atleast one uppercase & lowercase alphabet, number & special character',
    emptyConfirmPassword: 'Please enter confirm password',
    validSamePassword: "Password doesn't match, Please try again",
    emptyOtp: 'Please enter otp',
    validOtp: 'Invalid otp',
    emptyPhone: 'Please enter your phone number',
    emptyMobile: 'Please enter your mobile number',
    emptyFirstName: 'Please enter your first name',
    emptyLastName: 'Please enter your last name',
    emptyUsername: 'Please enter your username',
    validUsername:'Username can only accept letters, numbers, underscore and periods(.)',
    notValidNumberUsername:'Username can not contain only numbers',
    emptyAddress: 'Please enter your address',
    emptyCity: 'Please enter your city',
    emptyState: 'Please enter your state',
    emptyZipcode: 'Please enter your zipcode',
    emptyCountry: 'Please select your country',
    emptyLanguage: 'Please select your language',
  };
  